### ISSUE TITLE
Stairs & Stripped Logs Uncraftable

### ISSUE THREAD

**Issue by WenXin20** [LegendaryGeek/World-of-Wonder#7]
`Minecraft v1.15.2`
`Forge v31.2.5`
`World of Wonder v1.0.4`

Stairs seem to be uncraftable and stems are unable to be stripped using axes.

Also, stems are missing the minecraft logs tag, but that might be intentional.

**Comment by CosmicParticl** [comment]
Thanks for informing us! This will be resolved in the next update.
